CREATE TABLE IF NOT EXISTS keyword_to_link_link (
  id INT NOT NULL AUTO_INCREMENT ,
  keyword VARCHAR(225) CHARACTER SET utf8 NOT NULL,
  title VARCHAR(500) CHARACTER SET utf8 NOT NULL,
  url VARCHAR(500) CHARACTER SET utf8 NOT NULL,
  creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (id))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS keyword_to_link_link_display (
  id INT NOT NULL AUTO_INCREMENT ,
  link_id INT NOT NULL ,
  ip_address VARCHAR(100) NOT NULL ,
  creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (id))
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS keyword_to_link_link_click (
  id INT NOT NULL AUTO_INCREMENT ,
  link_id INT NOT NULL ,
  ip_address VARCHAR(100) NOT NULL ,
  creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (id))
ENGINE = InnoDB;
